const fs = require('fs');
const minify = require('html-minifier').minify;

const filePath = 'dist/visualkey/index.html';

fs.readFile(filePath, function (err, buf) {
  if (err) {
    console.log(err);
    return;
  }

  const originalValue = buf.toString();

  const minifiedValue = minify(originalValue, {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    conservativeCollapse: false,
    decodeEntities: true,
    html5: true,
    includeAutoGeneratedTags: false,
    keepClosingSlash: false,
    minifyCSS: true,
    minifyJS: true,
    preserveLineBreaks: false,
    preventAttributesEscaping: false,
    processConditionalComments: true,
    processScripts: ['text/html'],
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeEmptyElements: false,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: false,
    sortAttributes: true,
    sortClassName: true,
    trimCustomFragments: true,
    useShortDoctype: true,
  });

  fs.writeFile(filePath, minifiedValue, function (err) {
    if (err) {
      console.log(err);
      return;
    }

    const diff = originalValue.length - minifiedValue.length;

    const savings = originalValue.length ? ((100 * diff) / originalValue.length).toFixed(2) : 0;

    console.log(
      `Successfully minified '${filePath}'. Original size: ${originalValue.length}. Minified size: ${minifiedValue.length}. Savings: ${diff} (${savings}%)`,
    );
  });
});
