name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          lfs: true
      - run: git lfs checkout
      - uses: actions/setup-node@v3.1.1
      - run: npm install
      - run: npm run build
      - env:
          FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
        run: npx fleek site:deploy
