name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://visualkey.link
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          lfs: true
      - run: git lfs checkout
      - uses: actions/setup-node@v3.6.0
      - run: npm install
      - run: npm run build
      - run: npm run minify-index
      - run: npm run fix-ngsw-path
      - env:
          FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
        run: npm run deploy
