name: Deploy to PROD

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://visualkey.link
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          lfs: true
      - uses: actions/setup-node@v4.3.0
      - run: npm ci
      - run: npm run build:prod
      - env:
          SWA_CLI_DEPLOY_ENV: Production
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.SWA_CLI_DEPLOYMENT_TOKEN }}
        run: npm run deploy
